In [1]:
import numpy as np


In [14]:
a = np.array([0,0,2])

In [15]:
a

array([0, 0, 2])

In [18]:
b = np.broadcast_to(a,6)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,)  and requested shape (6,)

In [10]:
c = np.broadcast_to(np.array([1,2,3]), (10,3))
c

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
np.concatenate((b,c))

array([[0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [0, 0, 2],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
np.concatenate([np.empty((1,3)), np.array([1,2,3])[np.newaxis,...]])

array([[4.68142203e-310, 0.00000000e+000, 2.37151510e-322],
       [1.00000000e+000, 2.00000000e+000, 3.00000000e+000]])

In [28]:
a = [0,1,2]

In [29]:
a += [3,4,5]
a

[0, 1, 2, 3, 4, 5]