#### Use the ranster rensdering module to create ranster renders of test scene


In [1]:
import raster_relight as rr


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
import pprint
from matplotlib import pyplot as plt
from PIL import Image
import numpy as np
import os
import glob

In [4]:
output = rr.create_raster_images()

Bit depth used for depth remapping was 8
Loaded /home/dtetruash/Thesis/datasets/nerf-blender/nerf_synthetic/intrinsic_tester_sphere/lights_intrinsic_tester_sphere.json. Number of lights is 9
det(R) = 1.0000000311834887
R^T @ R = 
[[ 1.00000007e+00 -2.90236812e-08  8.29079916e-09]
 [-2.90236812e-08  1.00000000e+00 -3.13000683e-08]
 [ 8.29079916e-09 -3.13000683e-08  9.99999986e-01]]
Using the following intrinsics matrix:
K = 
[[1.11111103e+03 0.00000000e+00 4.00000000e+02]
 [0.00000000e+00 1.11111103e+03 4.00000000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
There are 263345 points with finite depth in the image.
Posed_points shape in porject func: (640000, 3)
Posed_points shape in raster: (263345, 3)


╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 output = rr.create_raster_images()                                                           │
│   2                                                                                              │
│                                                                                                  │
│ /home/dtetruash/Thesis/intrinsic-light-estimation/light_mlp/raster_relight.py:358 in             │
│ create_raster_images                                                                             │
│                                                                                                  │
│   355 │   albedo = np.asarray(images['albedo'])[..., :3].astype(np.float32) / 255.               │
│   356 │                                                                                          │
│   357 │   # Get Normals                                                                          │
│ ❱ 358 │   camera_normals = get_camera_space_normals(image_normal) * occupied_mask[..., np.newa   │
│   359 │   world_normals = get_world_space_normals(camera_normals, R)                             │
│   360 │                                                                                          │
│   361 │   # do this for the given light orientations, populate dict for output                   │
│                                                                                                  │
│ /home/dtetruash/Thesis/intrinsic-light-estimation/light_mlp/raster_relight.py:211 in             │
│ get_camera_space_normals                                                                         │
│                                                                                                  │
│   208 │                                                                                          │
│   209 │   # Translation and scaling needed to remap to [-1,1], [-1,1], and [-1,0] resp.          │
│   210 │   # (doing it like this for debug reasons)                                               │
│ ❱ 211 │   camera_normals = (camera_normals_pixels_normalized + shift) * scale                    │
│   212 │                                                                                          │
│   213 │   # Normalize the normals and zero non-occupied ones.                                    │
│   214 │   camera_normals_norms = np.linalg.norm(camera_normals, axis=-1)                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: operands could not be broadcast together with shapes (800,800,4) (3,)

In [4]:
for name, image in output:
    plt.imsave(f'raster_{name}.png'.lower(), image)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 for name, image in output:                                                                   │
│ ❱ 2 │   plt.imsave(f'raster_{name}.png'.lower(), image)                                          │
│   3                                                                                              │
│                                                                                                  │
│ /home/dtetruash/.miniconda3/envs/thesis/lib/python3.10/site-packages/matplotlib/pyplot.py:2200   │
│ in imsave                                                                                        │
│                                                                                                  │
│   2197                                                                                           │
│   2198 @_copy_docstring_and_deprecators(matplotlib.image.imsave)                                 │
│   2199 def imsave(fname, arr, **kwargs):                                                         │
│ ❱ 2200 │   return matplotlib.image.imsave(fname, arr, **kwargs)                                  │
│   2201                                                                                           │
│   2202                                                                                           │
│   2203 def matshow(A, fignum=None, **kwargs):                                                    │
│                                                                                                  │
│ /home/dtetruash/.miniconda3/envs/thesis/lib/python3.10/site-packages/matplotlib/image.py:1652 in │
│ imsave                                                                                           │
│                                                                                                  │
│   1649 │   │   else:                                                                             │
│   1650 │   │   │   sm = cm.ScalarMappable(cmap=cmap)                                             │
│   1651 │   │   │   sm.set_clim(vmin, vmax)                                                       │
│ ❱ 1652 │   │   │   rgba = sm.to_rgba(arr, bytes=True)                                            │
│   1653 │   │   if pil_kwargs is None:                                                            │
│   1654 │   │   │   pil_kwargs = {}                                                               │
│   1655 │   │   else:                                                                             │
│                                                                                                  │
│ /home/dtetruash/.miniconda3/envs/thesis/lib/python3.10/site-packages/matplotlib/cm.py:475 in     │
│ to_rgba                                                                                          │
│                                                                                                  │
│   472 │   │   │   │   │   raise ValueError("Third dimension must be 3 or 4")                     │
│   473 │   │   │   │   if xx.dtype.kind == 'f':                                                   │
│   474 │   │   │   │   │   if norm and (xx.max() > 1 or xx.min() < 0):                            │
│ ❱ 475 │   │   │   │   │   │   raise ValueError("Floating point image RGB values "                │
│   476 │   │   │   │   │   │   │   │   │   │    "must be in the 0..1 range.")                     │
│   477 │   │   │   │   │   if bytes:                                                              │
│   478 │   │   │   │   │   │   xx = (xx * 255).astype(np.uint8)                                   │
╰────────────────────────────────────────────────────────────

In [ ]:
output.sort()

In [ ]:
# read in reference GTs
path = '/home/dtetruash/Thesis/datasets/nerf-blender/nerf_synthetic/intrinsic_tester_sphere'
gt_files = glob.glob(f"{path}/*combined_*")
gt_files.sort()

gt_files

gt_images = [plt.imread(f) for f in gt_files]

In [ ]:
def two_plot(im0, im1, label0="", label1=""):
    plt.subplot(1, 2, 1)
    plt.title(label0)
    plt.imshow(im0)
    plt.subplot(1, 2, 2)
    plt.title(label1)
    plt.imshow(im1)
    fig1 = plt.gcf()
    plt.show()
    plt.draw()
    fig1.savefig(f"{label0.replace(' ', '-')}_{label1.replace(' ', '-')}.png".lower())

In [ ]:
# View and save the side-by-side figures
for i, v in enumerate(output):
    two_plot(gt_images[i], v[1], label0=f"GT {v[0]}", label1=f"Raster {v[0]} geometric")